### PR TITLE
(testing): add WebdriverIO harness

### PR DESCRIPTION
**Pull request by christian-bromann**
Adding WebdriverIO testing with Sauce Labs to the application.

### CODE REVIEW

**Comment by christian-bromann** [comment]
> * The tests running `wdio:sauce` all failed for me. I'm also not sure what these are.

Can you share the wdio logs on this one please? I am curious to see what went wrong here.

> * The component tests failed.

I will remove those.

**Comment by danielkellyio** [comment]
@christian-bromann 
This was the output. Is this what you're looking for or are there more detailed logs somewhere?
Screenshot 2023-07-31 at 10 39 02 AM

**Comment by christian-bromann** [comment]
> Is this what you're looking for or are there more detailed logs somewhere?

There must be a `logs` directory that contains a bunch of `wdio.logs`, ideally a log file from a worker, e.g. `wdio-0-0.log`

**Comment by danielkellyio** [comment]
@christian-bromann Here you go:
[logs.zip](https://github.com/vueschool/vue-forge-episode-4/files/12216744/logs.zip)

**Pull request merged**
